### ISSUE TITLE
not work with sbt 0.13.15

### ISSUE THREAD

**Issue by flisky** [foundweekends/giter8#297]
```
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.eclipse.jgit.util.FS.<clinit>(FS.java:112)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.setupWorkTree(BaseRepositoryBuilder.java:620)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:556)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:577)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:113)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:161)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at giter8.JgitHelper$.clone(JgitHelper.scala:116)
	at giter8.JgitHelper$.run(JgitHelper.scala:67)
	at giter8.JgitHelper$.run(JgitHelper.scala:80)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:33)
	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
	at scala.collection.immutable.List.find(List.scala:84)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jgit.util.FS.<clinit>(FS.java:112)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.setupWorkTree(BaseRepositoryBuilder.java:620)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:556)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:577)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:113)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:161)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at giter8.JgitHelper$.clone(JgitHelper.scala:116)
	at giter8.JgitHelper$.run(JgitHelper.scala:67)
	at giter8.JgitHelper$.run(JgitHelper.scala:80)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:33)
	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
	at scala.collection.immutable.List.find(List.scala:84)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
```

It works after downgrading to sbt 0.13.13

**Comment by flisky** [comment]
Ｍaybe it's just a conflicted with `sbt.version` from `project/build.properties`.

No more investigation, closing.
